### ISSUE TITLE
Chapitre 1 : Introduction

### ISSUE THREAD

**Issue by MadJlzz** [sfeir-open-source/sfeir-school-docker#1]
L'idée est de reprendre le contenu présent [ici](https://docs.google.com/presentation/d/1FG5V8AiUxCi0m41LE3mtKW22n1Oqm6MrU89TC9qEHK0/edit?usp=sharing) du chapitre "Introduction".

Il faut réduire l'historique de sorte à gagner du temps sur cette partie.

On pourrait aussi récupérer une idée que j'avais eu au niveau des titres pour une présentation que j'avais faites chez un client. [clic](https://docs.google.com/presentation/d/1WXztCy2-UAuUP56449YlooKS8_gERUJrMui44Qo4TPk/edit?usp=sharing)

Pour résumer :

1. reprendre les slides 8, 9, 10, 11, 12, 13, 14 ;
2. supprimer les slides 15, 16, 17

**Comment by zbbfufu** [comment]
Pensez aussi à prendre en compte les slides de la school sur 1 jours donnée par Jonathan [ici](https://docs.google.com/presentation/d/1e7y1VVJSSQawhIxf131-_VFZqt0vEwbVfkfCern3EYs/edit)
